{% set name = "wannier90" %}

# Temporary development snapshot from upstream develop branch.
# Replace with the official v4 release tag once available.
{% set version = "4.0.0.dev202606" %}
{% set commit = "d3772db24d216f44e089125726164e6880251da1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wannier-developers/wannier90/archive/{{ commit }}.tar.gz
  sha256: 79525d32736f1ad5d80a0f3c10bb941b7f723bc965d2fb99002d3bf5fce6d60a

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - make
  host:
    - libblas
    - liblapack
    - openmpi >=4.1.6,<5
  run:

test:
  commands:
    - test -x ${PREFIX}/bin/wannier90.x
    - test -x ${PREFIX}/bin/postw90.x

about:
  home: http://www.wannier.org/
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'The Maximally-Localised Generalised Wannier Functions Code'

  description: |
    Wannier90 is an open-source code (released under GPLv2) for
    generating maximally-localized Wannier functions and using them
    to compute advanced electronic properties of materials with high
    efficiency and accuracy.
  doc_url: https://github.com/wannier-developers/wannier90/tree/master/doc
  dev_url: https://github.com/wannier-developers/wannier90

extra:
  recipe-maintainers:
    - edan-bainglass
    - jan-janssen
    - mbercx
